name: Create Major Release

permissions:
  contents: write

on: workflow_dispatch

jobs:
  release:
    name: Create new major release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - name: Construct new version name
        id: newTag
        run: |
          git fetch --tags
          latest=$(git tag --sort=version:refname | tail -n 1)
          currVersion="${latest#v}"
          currVersion="${currVersion%%-*}"
          major=$(echo "$currVersion" | cut -d. -f1)
          major=$((major + 1))
          newVersion="${major}.0.0"
          echo "version=$newVersion" >> $GITHUB_OUTPUT
      - name: Build asset
        run: |
          npm ci
          npm install @angular/cli
          npx ng build --configuration=production
      - name: Bundle angular browser build
        run: |
          cd dist/QuantumMart/browser
          zip -r ../../../QuantumMart-v${{ steps.newTag.outputs.version }}.zip .
      - name: Upload new release
        run: |
          gh release create v${{ steps.newTag.outputs.version }} \
            --generate-notes \
            QuantumMart-v${{ steps.newTag.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
